/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guiObjects;

/**
 *
 * @author plcau
 */
import java.util.ArrayList;
import java.util.Iterator; 
import java.awt.GridBagConstraints;
import javax.swing.JPanel; 
import java.awt.Dimension; 
import Game.BuildableBody;
public class BuildableBodyButtonsPanel extends javax.swing.JPanel {
    
    protected ArrayList<BuildableBody> buildableBodyOptions; 
    
    /**
     * Creates new form BuildableBodyButtonsPanel
     */
    private BuildableBodyButtonsPanel(ArrayList<BuildableBody> _buildableBodyOptions) {
        buildableBodyOptions = _buildableBodyOptions; 
        initComponents();
    }
    
    public static BuildableBodyButtonsPanel newBuildableBodyButtonsPanel(ArrayList<BuildableBody> _buildableBodyOptions) {
        // Create new panel object; 
        BuildableBodyButtonsPanel newPanel = new BuildableBodyButtonsPanel(_buildableBodyOptions); 
        int horizontalSize = 0; 
        // Set up buffer / loop variables; 
        GridBagConstraints objectConstraints;
        BuildableBodyNavigationButton buffer;
        BuildableBody currentBuildableBody;
        
        // Number of buttons
        int buttonNumber;
        for (buttonNumber = 0; buttonNumber < newPanel.getBuildableBodyOptions().size(); buttonNumber++) {
            // Get the current buildable body; 
            currentBuildableBody = newPanel.getBuildableBodyOptions().get(buttonNumber); 
            // Define object layout constraints
            objectConstraints = new GridBagConstraints(); 
            objectConstraints.gridy = 0; 
            objectConstraints.gridx = buttonNumber; // Lay horizontally depending on their order in the initial arrayList. 
            objectConstraints.weighty = 1.0;
            objectConstraints.weightx = 0.0; 
            objectConstraints.fill = GridBagConstraints.VERTICAL; 
            
            // Create new navigation button and add it to the panel; 
            buffer = BuildableBodyNavigationButton.newBuildableBodyNavigationButton(currentBuildableBody); 
            newPanel.add(buffer.getJButton(), objectConstraints); 
            
            
        }
        
        // Add glue to fill in any potentially empty space to prevent potential streching of mainStructureMainPanel; 
        JPanel glue = new JPanel();
        glue.setOpaque(false); 
        GridBagConstraints glueConstraints = new GridBagConstraints();
        glueConstraints.gridx = buttonNumber + 1; // Set it to be present as very last entry of our panel
        glueConstraints.gridy = 0;  
        glueConstraints.weightx = 1.0; // Fully span horizontally to fill remaining space
        glueConstraints.weighty = 1.0; 
        glueConstraints.fill = GridBagConstraints.BOTH;
        newPanel.add(glue, glueConstraints);
        
        // Set horizontal preferred size for newPanel/JPanel to properly scroll in parent JScrollPane; 
        horizontalSize = BuildableBodyNavigationButton.BUTTON_IMAGE_WIDTH * (1+buttonNumber); 
        
        newPanel.setPreferredSize(new Dimension(horizontalSize, 100));
        newPanel.setMinimumSize(new Dimension(horizontalSize, 100));
        
        return newPanel;
    }
    
    public ArrayList<BuildableBody> getBuildableBodyOptions() {
        return this.buildableBodyOptions; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
