/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiObjects;

/**
 *
 * @author plcau
 */
import Game.Game;
import Game.*; 
import java.awt.BorderLayout;
import java.awt.Container; 
public class GameRootGui extends javax.swing.JFrame {    
    /** Game header title*/ 
    final static public String GAME_NAME = "Space Logistics Utilitarian Guidance System (S.L.U.G.S) v0.4.1"; 
    
    // Current BuildableBody being focused on currently focused object 
    public MainBodyContainer mainBodyContainer; 
    
    // Create new ResourceDisplayContainer for the Resource value sidebar; 
    public ResourceDisplayContainer resourceDisplayPanel = new ResourceDisplayContainer(); 
    /**
     * Creates new form GameRootGui
     */
    public GameRootGui() {
        
        initComponents();
        
        // Set mainBodyContainer as the Game's current base scope to start when initializing; 
        mainBodyContainer = new MainBodyContainer(Game.getCurrentScope()); 
        
        // Then add mainBodyContainer as the content of MainGamePanel; 
        MainGamePanel.add(mainBodyContainer, BorderLayout.NORTH); 
    }
    
    
    
    /**
     * Set current focus game panel to newContainer. 
     * @param newContainer A JPanel to set as the current new contents of MainGamePanel. 
     */
    public void setMainGamePanel(MainBodyContainer newContainer) {
        mainBodyContainer = newContainer; 
        MainGamePanel.removeAll(); 
        MainGamePanel.add(mainBodyContainer, BorderLayout.NORTH);
        MainGamePanel.revalidate();
        MainGamePanel.repaint();    
    }
    
    /**
     * Updates MainGamePanel's content with a new MainBodyContainer with an updated currentScope based off the current scope of the Game class. 
     */
    public void updateMainGamePanel() {
        System.out.println("Updating main game panel with current scope:" + Game.getCurrentScope().getIdentifier());
        this.setMainGamePanel(new MainBodyContainer(Game.getCurrentScope())); 
    }
    
    /**
     * Updates intrinsic UI objects specific to this (header elements) & revalidate/repaints it's entries. 
     */
    public void updateUI() {
        lblDateHeader.setText(Utilities.getDate(Game.gameDate));
        lblCurrentFocus.setText("Currently on: "+ Game.getCurrentScope().getDisplayName());
        repaint(); 
        revalidate(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        MainGamePanel = new javax.swing.JPanel();
        headerPanelContainer = new javax.swing.JPanel();
        lblDateHeader = new javax.swing.JLabel();
        lblCurrentFocus = new javax.swing.JLabel();
        ScrlResourceDisplay = new javax.swing.JScrollPane(resourceDisplayPanel);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuBtnSaveGame = new javax.swing.JMenuItem();
        mnuBtnExitGame = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        chkPauseGame = new javax.swing.JCheckBoxMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnuBtnTickgame = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resources");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(GAME_NAME);
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("mainGuiFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        MainGamePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MainGamePanel.setPreferredSize(new java.awt.Dimension(972, 218));
        MainGamePanel.setLayout(new java.awt.BorderLayout(5, 5));

        headerPanelContainer.setLayout(new java.awt.GridBagLayout());

        lblDateHeader.setText("Game Time");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 30);
        headerPanelContainer.add(lblDateHeader, gridBagConstraints);

        lblCurrentFocus.setText("Current Focus");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 30);
        headerPanelContainer.add(lblCurrentFocus, gridBagConstraints);

        ScrlResourceDisplay.setViewportView(resourceDisplayPanel);
        ScrlResourceDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ScrlResourceDisplay.setToolTipText("");
        ScrlResourceDisplay.setViewportBorder(null);
        ScrlResourceDisplay.setColumnHeaderView(jLabel1);
        ScrlResourceDisplay.setMaximumSize(new java.awt.Dimension(250, 590));
        ScrlResourceDisplay.setMinimumSize(new java.awt.Dimension(250, 590));
        ScrlResourceDisplay.setName(""); // NOI18N
        ScrlResourceDisplay.setPreferredSize(new java.awt.Dimension(250, 690));
        ScrlResourceDisplay.setRequestFocusEnabled(false);
        ScrlResourceDisplay.setVerifyInputWhenFocusTarget(false);
        ScrlResourceDisplay.setViewportView(resourceDisplayPanel);

        jMenu1.setText("Game");

        mnuBtnSaveGame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuBtnSaveGame.setText("Save Game");
        mnuBtnSaveGame.addActionListener(this::mnuBtnSaveGameActionPerformed);
        jMenu1.add(mnuBtnSaveGame);

        mnuBtnExitGame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PERIOD, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuBtnExitGame.setText("Exit Game");
        mnuBtnExitGame.addActionListener(this::mnuBtnExitGameActionPerformed);
        jMenu1.add(mnuBtnExitGame);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Settings");

        chkPauseGame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        chkPauseGame.setSelected(true);
        chkPauseGame.setText("Pause Game");
        chkPauseGame.addActionListener(this::chkPauseGameActionPerformed);
        jMenu2.add(chkPauseGame);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Debug Menu");
        jMenu6.addActionListener(this::jMenu6ActionPerformed);

        mnuBtnTickgame.setText("Manually tickGame()");
        mnuBtnTickgame.addActionListener(this::mnuBtnTickgameActionPerformed);
        jMenu6.add(mnuBtnTickgame);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainGamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
                    .addComponent(headerPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(ScrlResourceDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ScrlResourceDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(headerPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(MainGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void mnuBtnTickgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnTickgameActionPerformed
        // TODO add your handling code here:
        Game.tickGame(); 
    }//GEN-LAST:event_mnuBtnTickgameActionPerformed

    private void chkPauseGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPauseGameActionPerformed
        // TODO add your handling code here:
        Game.isPausedFlag = chkPauseGame.isSelected();
    }//GEN-LAST:event_chkPauseGameActionPerformed

    private void mnuBtnSaveGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnSaveGameActionPerformed
        // TODO add your handling code here:
        GameData.saveData();
    }//GEN-LAST:event_mnuBtnSaveGameActionPerformed

    // Function for closing frame window to automatically save game progress.
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        GameData.saveData();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void mnuBtnExitGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBtnExitGameActionPerformed
        // TODO add your handling code here:
        GameData.saveData();
        System.exit(0);
    }//GEN-LAST:event_mnuBtnExitGameActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainGamePanel;
    private javax.swing.JScrollPane ScrlResourceDisplay;
    private javax.swing.JCheckBoxMenuItem chkPauseGame;
    private javax.swing.JPanel headerPanelContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblCurrentFocus;
    private javax.swing.JLabel lblDateHeader;
    private javax.swing.JMenuItem mnuBtnExitGame;
    private javax.swing.JMenuItem mnuBtnSaveGame;
    private javax.swing.JMenuItem mnuBtnTickgame;
    // End of variables declaration//GEN-END:variables
}
