/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiObjects;

/**
 *
 * @author plcau
 */
import Game.Game;
import Game.*; 
import java.awt.BorderLayout;
import javax.swing.Box; 
import java.awt.Component; 
import java.awt.Container; 
import java.util.Random; 
import java.util.ArrayList; 
import java.util.Iterator; 
public class GameGuiContainer extends javax.swing.JFrame {    
    
    /**
     * Creates new form GameGuiContainer
     */
    public ResourceDisplayContainer resourceDisplayPanel = new ResourceDisplayContainer(); 
    
    public GameGuiContainer() {
        
        initComponents();
        
        // Set MainBodyContainer as current focus tab for now;
        MainGamePanel.add(new MainBodyContainer(), BorderLayout.NORTH); 
    }
    public void updateUI(Container ContainerObject) {
        ContainerObject.repaint();
        ContainerObject.revalidate(); 
    }
    
    /**
     * Set current focus game panel to newContainer. 
     * @param newContainer A JPanel to set as the current new contents of MainGamePanel. 
     */
    public void setMainGamePanel(javax.swing.JPanel newContainer) {
        MainGamePanel.removeAll(); 
        MainGamePanel.add(newContainer); 
    }
    
    public void updateUI() {
        lblDateHeader.setText(Utilities.getDate(Game.gameDate));
        repaint(); 
        revalidate(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MainGamePanel = new javax.swing.JPanel();
        headerPanelContainer = new javax.swing.JPanel();
        lblDateHeader = new javax.swing.JLabel();
        ScrlResourceDisplay = new javax.swing.JScrollPane(resourceDisplayPanel);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resources");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(Game.GAME_NAME);
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("mainGuiFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        MainGamePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MainGamePanel.setPreferredSize(new java.awt.Dimension(972, 218));
        MainGamePanel.setLayout(new java.awt.BorderLayout(5, 5));

        headerPanelContainer.setLayout(new java.awt.GridBagLayout());

        lblDateHeader.setText("Game Time");
        headerPanelContainer.add(lblDateHeader, new java.awt.GridBagConstraints());

        ScrlResourceDisplay.setViewportView(resourceDisplayPanel);
        ScrlResourceDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ScrlResourceDisplay.setToolTipText("");
        ScrlResourceDisplay.setViewportBorder(null);
        ScrlResourceDisplay.setColumnHeaderView(jLabel1);
        ScrlResourceDisplay.setMaximumSize(new java.awt.Dimension(250, 590));
        ScrlResourceDisplay.setMinimumSize(new java.awt.Dimension(250, 590));
        ScrlResourceDisplay.setName(""); // NOI18N
        ScrlResourceDisplay.setPreferredSize(new java.awt.Dimension(250, 690));
        ScrlResourceDisplay.setRequestFocusEnabled(false);
        ScrlResourceDisplay.setVerifyInputWhenFocusTarget(false);
        ScrlResourceDisplay.setViewportView(resourceDisplayPanel);

        jMenu1.setText("Game");

        jMenuItem2.setText("Save Game");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Exit Game");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Load Game");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Settings");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("System Navigation");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Research");
        jMenuBar1.add(jMenu4);

        jMenu6.setText("Debug Menu");
        jMenu6.addActionListener(this::jMenu6ActionPerformed);

        jMenuItem1.setText("Manually tickGame()");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu6.add(jMenuItem1);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainGamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
                    .addComponent(headerPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(ScrlResourceDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ScrlResourceDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(headerPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(MainGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Game.tickGame(); 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainGamePanel;
    private javax.swing.JScrollPane ScrlResourceDisplay;
    private javax.swing.JPanel headerPanelContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel lblDateHeader;
    // End of variables declaration//GEN-END:variables
}
