/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guiObjects;

/**
 * Container JPanel for when a BuildableBody is currently being focused on. 
 * @author plcau
 */
import Game.BuildableBody; 
import java.awt.GridBagConstraints;
import javax.swing.JPanel;
public class MainBodyContainer extends javax.swing.JPanel {
    
    // Current BuildableBody that is being focused on. 
    BuildableBody buildableBodyFocus; 
    
    // Panel declarations for JCardLayout (not implemented)
    protected final static String STRUCTURE_PANEL = "structure";
    
    
    /**
     * Creates new form mainContainer
     */
    public MainBodyContainer(BuildableBody _buildableBodyFocus) {
        
        // Set current buildableBodyFocus as the input; then initialize components
        buildableBodyFocus = _buildableBodyFocus; 
        initComponents();
        
        
        // Update components based on buildableBodyFocus's data. 
        updateStructureDisplayPanel(); 
        updateBodyImagePanel();
        updateBodyDescriptionPanel(); 
        updateBodyNavigationPanel(); 
        pnlMainScreenContent.add(pnlStructureDisplay, MainBodyContainer.STRUCTURE_PANEL);
    }
    
    public void updateMainBodyContainer(BuildableBody _newScope) {
        this.buildableBodyFocus = _newScope; 
        
        pnlMainScreenContent.removeAll();
        updateStructureDisplayPanel(); 
        updateBodyImagePanel();
        updateBodyDescriptionPanel(); 
        updateBodyNavigationPanel(); 
        pnlMainScreenContent.add(pnlStructureDisplay, MainBodyContainer.STRUCTURE_PANEL);
    }
    
    /**
     * Updates the central updateStructureDisplaypanel via clearing it and re-adding new object when required. 
     */
    public void updateStructureDisplayPanel() {
        // Clear all objects. 
        System.out.println("=========");
        System.out.println("Structure panel updated");
        System.out.println("Structures to display amount:" + this.buildableBodyFocus.getBodyStructures().size());
        pnlStructureDisplay.removeAll();
        
        // Set up GridBagConstraints for the main StructureMainPanel within StructureDisplay
        GridBagConstraints panelContentGridBagConstraints = new GridBagConstraints(); 
        
        // Position in [0,0]; or in top left position of Grid Bag Layout's table
        panelContentGridBagConstraints.gridx = 0; 
        panelContentGridBagConstraints.gridy = 0; 
        
        // Set to fill horizontally and vertically; 
        panelContentGridBagConstraints.fill = GridBagConstraints.BOTH;
        
        // Set the main content to be equal to a structureMainPanel object with the current focus buildableBody's structures; then add to the display panel; 
        StructureMainPanel mainContent = StructureMainPanel.newStructureMainPanel(buildableBodyFocus.getBodyStructures(), buildableBodyFocus);
        pnlStructureDisplay.add(mainContent, panelContentGridBagConstraints); 
        
        // Add glue to fill in any potentially empty space to prevent potential streching of mainStructureMainPanel; 
        JPanel glue = new JPanel();
        glue.setOpaque(false); 
        GridBagConstraints glueConstraints = new GridBagConstraints();
        glueConstraints.gridx = 0; 
        glueConstraints.gridy = 2;  // Set it to be present at the very last row of our display; i.e. index + 1; 
        glueConstraints.weightx = 1.0; // Fully span horizontally
        glueConstraints.weighty = 1.0; // Take highest priority within Grid Bag Layout vertically, take up all remaining space  
        glueConstraints.fill = GridBagConstraints.BOTH;
        pnlStructureDisplay.add(glue, glueConstraints);
    }
    
    /**
     * Updates the image present within lblPlanetAppearanceImage 
     */
    public void updateBodyImagePanel() {
        // Get image / icon from assets directory; then set to the icon of lblPlanetAppearanceImage. 
        javax.swing.ImageIcon imageToDisplay = new javax.swing.ImageIcon(getClass().getResource(buildableBodyFocus.getReferenceDataTableEntry().getObjectIconDirectory()));
        lblPlanetAppearanceImage.setIcon(imageToDisplay); 
    }
    
    /**
     * Updates the txtBodyDescriptionArea display text with the current description of the BuildableBody. 
     */
    public void updateBodyDescriptionPanel() {
        txtBodyDescriptionArea.setText(buildableBodyFocus.getDisplayDescription());
    }
    
    public void updateBodyNavigationPanel() {
        PnlSystemNavigation.removeAll();
        PnlSystemNavigation.add(BuildableBodyButtonsPanel.newBuildableBodyButtonsPanel(Game.Game.getBuildableBodyContainerTable())); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        MenuNavigationBar = new javax.swing.JMenuBar();
        MnuBtnSurface = new javax.swing.JMenu();
        pnlStructureDisplay = new javax.swing.JPanel();
        pnlOrbitalDisplay = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlVesselDisplay = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PnlSystemNavigation = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        PnlImage = new javax.swing.JPanel();
        lblPlanetAppearanceImage = new javax.swing.JLabel();
        lblPlanetAppearance = new javax.swing.JLabel();
        PnlImageDescription = new javax.swing.JPanel();
        lblBodyDescriptionHeader = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBodyDescriptionArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        PnlMainScreen = new javax.swing.JPanel();
        pnlMainScreenContent = new javax.swing.JPanel();

        MnuBtnSurface.setText("Surface");
        MnuBtnSurface.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                MnuBtnSurfaceMenuSelected(evt);
            }
        });
        MenuNavigationBar.add(MnuBtnSurface);

        pnlStructureDisplay.setLayout(new java.awt.GridBagLayout());

        pnlOrbitalDisplay.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("pnlOrbitalDisplay");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 0, 42, 0);
        pnlOrbitalDisplay.add(jLabel2, gridBagConstraints);

        pnlVesselDisplay.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("pnlVesselDisplay");
        pnlVesselDisplay.add(jLabel3, new java.awt.GridBagConstraints());

        setPreferredSize(new java.awt.Dimension(975, 672));
        setRequestFocusEnabled(false);

        PnlSystemNavigation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PnlSystemNavigation.setMinimumSize(new java.awt.Dimension(2, 100));
        PnlSystemNavigation.setLayout(new java.awt.GridBagLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/placeholderPlanet.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(90, 90));
        jButton1.setMinimumSize(new java.awt.Dimension(90, 90));
        jButton1.setPreferredSize(new java.awt.Dimension(90, 90));
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        PnlSystemNavigation.add(jButton1, new java.awt.GridBagConstraints());

        PnlImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PnlImage.setMinimumSize(new java.awt.Dimension(200, 200));
        PnlImage.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        PnlImage.add(lblPlanetAppearanceImage, gridBagConstraints);

        lblPlanetAppearance.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblPlanetAppearance.setText("Body Appearance");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        PnlImage.add(lblPlanetAppearance, gridBagConstraints);

        PnlImageDescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PnlImageDescription.setMinimumSize(new java.awt.Dimension(200, 356));
        PnlImageDescription.setPreferredSize(new java.awt.Dimension(200, 356));
        PnlImageDescription.setLayout(new java.awt.GridBagLayout());

        lblBodyDescriptionHeader.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblBodyDescriptionHeader.setText("Body Description");
        PnlImageDescription.add(lblBodyDescriptionHeader, new java.awt.GridBagConstraints());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtBodyDescriptionArea.setColumns(20);
        txtBodyDescriptionArea.setLineWrap(true);
        txtBodyDescriptionArea.setRows(5);
        txtBodyDescriptionArea.setToolTipText("");
        txtBodyDescriptionArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtBodyDescriptionArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        PnlImageDescription.add(jScrollPane2, gridBagConstraints);

        jScrollPane1.setBorder(null);

        PnlMainScreen.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints MenuBarGridBagConstraints = new java.awt.GridBagConstraints();
        MenuBarGridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        MenuBarGridBagConstraints.gridx = 0;
        MenuBarGridBagConstraints.gridy = 0;
        PnlMainScreen.add(MenuNavigationBar, MenuBarGridBagConstraints);

        pnlMainScreenContent.setBackground(new java.awt.Color(204, 102, 0));
        pnlMainScreenContent.setToolTipText("");
        pnlMainScreenContent.setLayout(new java.awt.CardLayout());
        java.awt.GridBagConstraints contentGridBagConstraints = new java.awt.GridBagConstraints();
        contentGridBagConstraints.gridx = 0;
        contentGridBagConstraints.gridy = 1;
        contentGridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        contentGridBagConstraints.weightx = 1.0;
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        PnlMainScreen.add(pnlMainScreenContent, gridBagConstraints);

        jScrollPane1.setViewportView(PnlMainScreen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlSystemNavigation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PnlImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PnlImageDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlSystemNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PnlImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(PnlImageDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MnuBtnSurfaceMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MnuBtnSurfaceMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_MnuBtnSurfaceMenuSelected

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuNavigationBar;
    private javax.swing.JMenu MnuBtnSurface;
    private javax.swing.JPanel PnlImage;
    private javax.swing.JPanel PnlImageDescription;
    private javax.swing.JPanel PnlMainScreen;
    private javax.swing.JPanel PnlSystemNavigation;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBodyDescriptionHeader;
    private javax.swing.JLabel lblPlanetAppearance;
    private javax.swing.JLabel lblPlanetAppearanceImage;
    private javax.swing.JPanel pnlMainScreenContent;
    private javax.swing.JPanel pnlOrbitalDisplay;
    private javax.swing.JPanel pnlStructureDisplay;
    private javax.swing.JPanel pnlVesselDisplay;
    private javax.swing.JTextArea txtBodyDescriptionArea;
    // End of variables declaration//GEN-END:variables
}
