/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guiObjects;

/**
 *
 * @author plcau
 */
import java.util.ArrayList; 
import java.util.Iterator; 
import Game.Resource; 
import Game.Game; 
import java.awt.GridBagConstraints; 
import javax.swing.JPanel; 
public class ResourceDisplayContainer extends javax.swing.JPanel {
    
    protected ArrayList<Resource> currentResourceTable; 
    int verticalSpace = 0; 
    public GridBagConstraints gridBagConstraints = new GridBagConstraints();
    
    /**
     * Creates new form ResourceDisplayComponent
     */
    public ResourceDisplayContainer() {
        
        initComponents();
        readNewResourceTable(Game.getCurrentScope().getBodyResourceStorage()); 
        
    }
    
    public void readNewResourceTable(ArrayList<Resource> resourceTable) {
        
        verticalSpace = 0;
        Resource currentResource; 
        JPanel bufferPanel;
        this.currentResourceTable = resourceTable; 
        for (int index = 0; index < resourceTable.size(); index++){
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.weightx = 1.0;
            gridBagConstraints.weighty = 0.0;
            
            gridBagConstraints.gridy = index; 
            gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
            gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        
            verticalSpace += ResourceDisplayPanel.VERTICAL_SIZING; 
            currentResource = resourceTable.get(index); 
            currentResource.updateResourceDisplay(index);
            bufferPanel = currentResource.getResourceDisplayPanel(); 
            add(bufferPanel,gridBagConstraints);
            
        }
        System.out.println(verticalSpace);
        // Add glue to bottom of layout: 
        javax.swing.JPanel glue = new javax.swing.JPanel();
        glue.setOpaque(false);
        java.awt.GridBagConstraints glueConstraints = new java.awt.GridBagConstraints();
        glueConstraints.gridx = 0;
        glueConstraints.gridy = resourceTable.size(); // Row right below your last item
        glueConstraints.weightx = 1.0;
        glueConstraints.weighty = 1.0; // This absorbs all remaining empty space!
        glueConstraints.fill = GridBagConstraints.BOTH;
        add(glue, glueConstraints);
        
        setPreferredSize(new java.awt.Dimension(220,verticalSpace));
        //setMaximumSize(new java.awt.Dimension(190,Integer.MAX_VALUE));
        
        
        this.validate(); 
        this.repaint();
        
    }
    
    public ArrayList<Resource> getCurrentResourceTable() {
        return this.currentResourceTable; 
    }
    
    
    public void clearResourceDisplay() {
        // Clear all objects from GUI first
        this.removeAll();
        
        // Then iterate through all resource objects and destroy their instances of the GUI to prevent memory leaks 
        Iterator resourceIterator = this.getCurrentResourceTable().iterator(); 
        Resource currentResource; 
        while (resourceIterator.hasNext()){
            currentResource = (Resource) resourceIterator.next(); 
            
            // Destroy GUI object linked to Resource object. 
            currentResource.destroyResourceDisplay();
        }
        // Add c

        // Validate layout
        
        
        this.validate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(220, Integer.MAX_VALUE));
        setMinimumSize(new java.awt.Dimension(220, 0));
        setPreferredSize(new java.awt.Dimension(300, 100));
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
