package guiObjects;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


import Game.Resource; 
import java.math.BigDecimal; 
import java.awt.Container; 
/**
 * A small lightweight component meant for displaying Resource objects. 
 * @author plcau
 */
public class ResourceDisplayPanel extends javax.swing.JPanel {
    
    private Resource resourceToDisplay; 
    private java.awt.Color effectiveColor = GuiColors.RESOURCE_BACKGROUND_COLOR1;  
    private int index;  
    public final static int VERTICAL_SIZING = 22;  
    /**
     * Creates a new Resource Display Panel object based off an input _resourceToDisplay; 
     * @param _resourceToDisplay The resource object to display data from. 
     */
    
    
    private ResourceDisplayPanel(Resource _resourceToDisplay, int _index) {
        System.out.println("Please work");
        resourceToDisplay = _resourceToDisplay; 
        index = _index; 
        initComponents();
        
    }
    public static ResourceDisplayPanel newResourceDisplayPanel(Resource _resourceToDisplay, int _index) {
        ResourceDisplayPanel output = new ResourceDisplayPanel(_resourceToDisplay, _index); 
        return output; 
    }
    
    
    public void updateValue() {
        if (resourceToDisplay.getPreviousResourceValue() == 0) {
            lblDeltaResource.setText("+0.0/day"); 
        }
        else {
            lblDeltaResource.setText(String.valueOf(resourceToDisplay.getDeltaResource()) + "/day"); 
        }
        lblResourceAmount.setText(Double.toString(resourceToDisplay.getResourceAmount()));
        updateDisplay(lblResourceAmount); 
        
    }
    
    public void updateColor() {
        System.out.println(this.index%2);
        switch(this.index%2) {
            case 0 -> effectiveColor = GuiColors.RESOURCE_BACKGROUND_COLOR1;
            case 1 -> effectiveColor = GuiColors.RESOURCE_BACKGROUND_COLOR2; 
        }
        this.setBackground(effectiveColor); 
        updateDisplay(this); 
    }
    
    public void updateDisplay(Container uiToUpdate) {
        uiToUpdate.validate();
        uiToUpdate.repaint();
    }
    
    public void setIndex(int _index) {
        this.index = _index; 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblResourceDisplayName = new javax.swing.JLabel();
        lblResourceAmount = new javax.swing.JLabel();
        lblDeltaResource = new javax.swing.JLabel();

        setBackground(effectiveColor);
        setMaximumSize(new java.awt.Dimension(230, 20));
        setMinimumSize(new java.awt.Dimension(230, 15));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(300,VERTICAL_SIZING));
        setLayout(new java.awt.GridBagLayout());

        lblResourceDisplayName.setBackground(effectiveColor);
        lblResourceDisplayName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblResourceDisplayName.setForeground(GuiColors.BASE_TEXT_COLOR);
        lblResourceDisplayName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblResourceDisplayName.setText(resourceToDisplay.getDisplayName());
        lblResourceDisplayName.setAlignmentX(0.5F);
        lblResourceDisplayName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblResourceDisplayName.setMaximumSize(new java.awt.Dimension(100, 16));
        lblResourceDisplayName.setMinimumSize(new java.awt.Dimension(100, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(lblResourceDisplayName, gridBagConstraints);

        lblResourceAmount.setBackground(effectiveColor);
        lblResourceAmount.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblResourceAmount.setForeground(GuiColors.BASE_TEXT_COLOR);
        lblResourceAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblResourceAmount.setText(Double.toString(resourceToDisplay.getResourceAmount()));
        lblResourceAmount.setAlignmentX(0.5F);
        lblResourceAmount.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblDeltaResource.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(lblResourceAmount, gridBagConstraints);

        lblDeltaResource.setBackground(effectiveColor);
        lblDeltaResource.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDeltaResource.setForeground(GuiColors.BASE_TEXT_COLOR);
        lblDeltaResource.setText("0.0/day");
        lblDeltaResource.setAlignmentX(0.5F);
        lblDeltaResource.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblDeltaResource.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        lblDeltaResource.setMaximumSize(new java.awt.Dimension(100, 16));
        lblDeltaResource.setMinimumSize(new java.awt.Dimension(100, 16));
        lblDeltaResource.setPreferredSize(new java.awt.Dimension(100, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        add(lblDeltaResource, gridBagConstraints);
        lblDeltaResource.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDeltaResource;
    private javax.swing.JLabel lblResourceAmount;
    private javax.swing.JLabel lblResourceDisplayName;
    // End of variables declaration//GEN-END:variables
}
