package guiObjects;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


import Game.Resource; 
import java.math.BigDecimal; 
import java.awt.Container; 
/**
 * A small lightweight component meant for displaying Resource objects. 
 * @author plcau
 */
public class ResourceDisplayPanel extends javax.swing.JPanel {
    
    /**Current Resource object to display */
    private Resource resourceToDisplay; 
    
    /** Current color to use as a background (set as default value to start)*/
    private java.awt.Color effectiveColor = GuiConfigs.RESOURCE_BACKGROUND_COLOR1;  
    
    /** Index of this object within the parent container (used for alternating colors) */
    private int index;  
    
    // Determined via trial and error; increase/decrease to change vertical spacing of ResourceDisplayPanels. 
    /** Vertical sizing of this object in terms of setting preferred size*/
    public final static int VERTICAL_SIZING = 22;  
    
    
    
    /**
     * Creates a new Resource Display Panel object based off an input _resourceToDisplay; 
     * @param _resourceToDisplay The resource object to display data from. 
     */
    private ResourceDisplayPanel(Resource _resourceToDisplay, int _index) {
        resourceToDisplay = _resourceToDisplay; 
        index = _index; 
        
        initComponents();
        
        // Set tooltip text as the display description of the resource.
        this.lblResourceDisplayName.setToolTipText(resourceToDisplay.getDisplayDescription());
        
        // Update colros and update display.
        updateColor(); 
        updateDisplay(this);
        
    }
    
    /**
     * Creates a new ResourceDisplayPanel object returns the corresponding JPanel/ResourceDisplayPanel. 
     * @param _resourceToDisplay Resource object for this object to get it's display data from.
     * @param _index The display index of this object for alternating colors. 
     * @return 
     */
    public static ResourceDisplayPanel newResourceDisplayPanel(Resource _resourceToDisplay, int _index) {
        ResourceDisplayPanel output = new ResourceDisplayPanel(_resourceToDisplay, _index); 
        return output; 
    }
    
    /**
     * Updates the display values present within this ResourceDisplayPanel.
     */
    public void updateValue() {
        // If the previous resource value == 0; that is our panel was just initialized/is just 0; set to 0.0/day as a placeholder.
        String deltaResourceOutput; 
        String resourceAmountOutput;
        if (resourceToDisplay.getPreviousResourceValue() == 0) {
            deltaResourceOutput = "0.0/day"; 
            lblDeltaResource.setText(deltaResourceOutput); 
        }
        // If there actually was a previous value, set the delta value to be; "Sign DeltaValue / day".
        else {
            deltaResourceOutput = Game.Utilities.getSign(resourceToDisplay.getDeltaResource());
            deltaResourceOutput = deltaResourceOutput + " " + String.valueOf(resourceToDisplay.getDeltaResource()); 
            deltaResourceOutput += " / day";
            lblDeltaResource.setText(deltaResourceOutput); 
        }
        // Set current resource amount displayed to current resource amount;
        resourceAmountOutput = Double.toString(resourceToDisplay.getResourceAmount());
        lblResourceAmount.setText(resourceAmountOutput);
        
        // Update colors and display as needed. 
        updateColor();
        updateDisplay(lblResourceAmount); 
        
    }
    
    /**
     * Updates the background color of this Object based on it's index; 
     */
    public void updateColor() {
        
        // Alternate background color between two choices; then set that to be the background color of our panel. 
        switch(this.index%2) {
            case 0 -> effectiveColor = GuiConfigs.RESOURCE_BACKGROUND_COLOR1;
            case 1 -> effectiveColor = GuiConfigs.RESOURCE_BACKGROUND_COLOR2; 
        }
        this.setBackground(effectiveColor); 
        updateDisplay(this); 
    }
    
    public void updateDisplay(Container uiToUpdate) {
        uiToUpdate.validate();
        uiToUpdate.repaint();
    }
    
    public void setIndex(int _index) {
        this.index = _index; 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblResourceDisplayName = new javax.swing.JLabel();
        lblResourceAmount = new javax.swing.JLabel();
        lblDeltaResource = new javax.swing.JLabel();

        setBackground(effectiveColor);
        setMaximumSize(new java.awt.Dimension(230, 22));
        setMinimumSize(new java.awt.Dimension(230, 17));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(300,VERTICAL_SIZING));
        setLayout(new java.awt.GridBagLayout());

        lblResourceDisplayName.setBackground(effectiveColor);
        lblResourceDisplayName.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblResourceDisplayName.setForeground(guiObjects.GuiConfigs.BASE_TEXT_COLOR);
        lblResourceDisplayName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblResourceDisplayName.setText(resourceToDisplay.getDisplayName());
        lblResourceDisplayName.setAlignmentX(0.5F);
        lblResourceDisplayName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblResourceDisplayName.setMaximumSize(new java.awt.Dimension(100, 16));
        lblResourceDisplayName.setMinimumSize(new java.awt.Dimension(100, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(lblResourceDisplayName, gridBagConstraints);

        lblResourceAmount.setBackground(effectiveColor);
        lblResourceAmount.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblResourceAmount.setForeground(guiObjects.GuiConfigs.BASE_TEXT_COLOR);
        lblResourceAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblResourceAmount.setText(Double.toString(resourceToDisplay.getResourceAmount()));
        lblResourceAmount.setAlignmentX(0.5F);
        lblResourceAmount.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblDeltaResource.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(lblResourceAmount, gridBagConstraints);

        lblDeltaResource.setBackground(effectiveColor);
        lblDeltaResource.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblDeltaResource.setForeground(guiObjects.GuiConfigs.BASE_TEXT_COLOR);
        lblDeltaResource.setText("0.0/day");
        lblDeltaResource.setAlignmentX(0.5F);
        lblDeltaResource.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblDeltaResource.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        lblDeltaResource.setMaximumSize(new java.awt.Dimension(100, 16));
        lblDeltaResource.setMinimumSize(new java.awt.Dimension(100, 16));
        lblDeltaResource.setPreferredSize(new java.awt.Dimension(100, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        add(lblDeltaResource, gridBagConstraints);
        lblDeltaResource.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDeltaResource;
    private javax.swing.JLabel lblResourceAmount;
    private javax.swing.JLabel lblResourceDisplayName;
    // End of variables declaration//GEN-END:variables
}
