package guiObjects;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author plcau
 */
import Game.Resource; 
import java.lang.Math; 
import javax.swing.Box; 
import java.awt.Component; 
import java.awt.Dimension; 
import java.math.BigDecimal; 
public class SingleResourceDisplayPanel extends javax.swing.JPanel {
    
    
    private Resource resourceToDisplay; 
    private double previousResourceValue = 0;
    private final Component textValueSpacing = Box.createRigidArea(new Dimension(20,0));
    private final static java.awt.Color backgroundColor1 = new java.awt.Color(200,200,200);
    private final static java.awt.Color backgroundColor2 = new java.awt.Color(150,150,150); 
    private java.awt.Color effectiveColor = backgroundColor1; // by defualt use first color..?  
    private int index; 
    private final Component glueComponent = Box.createGlue(); 
    private double currentResourceValue; 
    /**
     * Creates new form ResourceDisplayPanel
     */
    public SingleResourceDisplayPanel(Resource _resourceToDisplay) {
        resourceToDisplay = _resourceToDisplay; 
        initComponents();
        lblResourceDisplayName.setText(resourceToDisplay.getDisplayName()); 
        currentResourceValue = resourceToDisplay.getResourceAmount(); 
        lblResourceAmount.setText(BigDecimal.valueOf(currentResourceValue).toString()); 
        
    }
    
    public void updateValue() {
        if (previousResourceValue == 0) {
            System.out.println(previousResourceValue);
            previousResourceValue = resourceToDisplay.getResourceAmount(); 
            lblDeltaResource.setText("+0.0/day"); 
        }
        else {
            double deltaResource = 0.0; 
            System.out.println(previousResourceValue);
            deltaResource = resourceToDisplay.getResourceAmount() - previousResourceValue; 
            System.out.println(deltaResource);
            System.out.println("test");
            lblDeltaResource.setText(String.valueOf(deltaResource) + "/day"); 
        }
        lblResourceAmount.setText(String.valueOf(resourceToDisplay.getResourceAmount()));
        lblDeltaResource.validate();
        lblDeltaResource.repaint(); 
        
    }
    
    public void updateColor() {
        System.out.println(this.index%2);
        switch(this.index%2) {
            case 0:
                effectiveColor = backgroundColor2; 
                
                break; 
            case 1: 
                effectiveColor = backgroundColor1;
                break; 
        }
        this.setBackground(effectiveColor); 
        this.updateDisplay(); 
    }
    
    public void updateDisplay() {
        this.validate();
        this.repaint();
    }
    
    public void setIndex(int _index) {
        this.index = _index; 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblResourceDisplayName = new javax.swing.JLabel();
        lblResourceAmount = new javax.swing.JLabel();
        lblDeltaResource = new javax.swing.JLabel();

        setBackground(effectiveColor);
        setMaximumSize(new java.awt.Dimension(300, 20));
        setMinimumSize(new java.awt.Dimension(300, 15));
        setLayout(new java.awt.GridBagLayout());

        lblResourceDisplayName.setBackground(effectiveColor);
        lblResourceDisplayName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblResourceDisplayName.setForeground(GuiColors.BASE_TEXT_COLOR);
        lblResourceDisplayName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblResourceDisplayName.setText("Resource Name");
        lblResourceDisplayName.setAlignmentX(0.5F);
        lblResourceDisplayName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblResourceDisplayName.setMaximumSize(new java.awt.Dimension(100, 16));
        lblResourceDisplayName.setMinimumSize(new java.awt.Dimension(100, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(lblResourceDisplayName, gridBagConstraints);

        lblResourceAmount.setBackground(effectiveColor);
        lblResourceAmount.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblResourceAmount.setForeground(GuiColors.BASE_TEXT_COLOR);
        lblResourceAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblResourceAmount.setText("Resource Amount ");
        lblResourceAmount.setAlignmentX(0.5F);
        lblResourceAmount.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblDeltaResource.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(lblResourceAmount, gridBagConstraints);

        lblDeltaResource.setBackground(effectiveColor);
        lblDeltaResource.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDeltaResource.setForeground(GuiColors.BASE_TEXT_COLOR);
        lblDeltaResource.setText("0.0/day");
        lblDeltaResource.setAlignmentX(0.5F);
        lblDeltaResource.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblDeltaResource.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        lblDeltaResource.setMaximumSize(new java.awt.Dimension(100, 16));
        lblDeltaResource.setMinimumSize(new java.awt.Dimension(100, 16));
        lblDeltaResource.setPreferredSize(new java.awt.Dimension(100, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(lblDeltaResource, gridBagConstraints);
        lblDeltaResource.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDeltaResource;
    private javax.swing.JLabel lblResourceAmount;
    private javax.swing.JLabel lblResourceDisplayName;
    // End of variables declaration//GEN-END:variables
}
