/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guiObjects;

/**
 *
 * @author plcau
 */
import Game.Structure; 
import Game.BuildableBody;
import Game.Resource; 
import javax.swing.JOptionPane; 
import javax.swing.JDialog; 
import java.awt.Dialog.ModalityType; 
import javax.swing.SwingUtilities; 
import java.awt.Component; 
public class StructurePopupDialog extends javax.swing.JPanel {
    
    /**
     * Creates new form StructurePopupDialog
     */
    Structure currentStructure; 
    private StructurePopupDialog(Structure _currentStructure) {
        currentStructure = _currentStructure; 
        initComponents();
    }
    public static StructurePopupDialog newStructurePopupDialog(Structure _currentStructure) {
        return new StructurePopupDialog(_currentStructure);
    }
    
    public static void newStructurePopupDialogWindow(Structure _currentStructure, Component parentComponent) {
        // Create new JDialog object, using SwingUtilities to get the highest most window ancestor of the parent component. 
        JDialog jDialogToDisplay = new JDialog(SwingUtilities.getWindowAncestor(parentComponent), ModalityType.APPLICATION_MODAL);
        
        // Add this class's JPanel into the Frame of the JDialog object and sets it to the east; 
        jDialogToDisplay.add(StructurePopupDialog.newStructurePopupDialog(_currentStructure), java.awt.BorderLayout.WEST); 
        
        // Prevent resizing; 
        jDialogToDisplay.setResizable(false);
        
        // Set title to be the display name of the current structure; 
        jDialogToDisplay.setTitle(_currentStructure.getDisplayName() + " Management");
        
        // Calculates layout
        jDialogToDisplay.pack(); 
        
        jDialogToDisplay.setLocationRelativeTo(SwingUtilities.getWindowAncestor(parentComponent));
        jDialogToDisplay.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblInputOutput = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInputOutputArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        lblEnabled = new javax.swing.JLabel();
        lblDisabled = new javax.swing.JLabel();
        txtCurrentlyEnabled = new javax.swing.JTextField();
        txtCurrentlyDisabled = new javax.swing.JTextField();
        btnConfirmConfiguration = new javax.swing.JButton();
        lblConfigurationHeader = new javax.swing.JLabel();
        btnBuildStructure = new javax.swing.JButton();
        btnDeconstructStructure = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        lblInputOutput.setText("Current Resource Input & Output: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 6, 10);
        add(lblInputOutput, gridBagConstraints);

        txtInputOutputArea.setEditable(false);
        txtInputOutputArea.setColumns(20);
        txtInputOutputArea.setLineWrap(true);
        txtInputOutputArea.setRows(5);
        txtInputOutputArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtInputOutputArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 10);
        add(jScrollPane1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblEnabled.setText("Structure Amount:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(lblEnabled, gridBagConstraints);

        lblDisabled.setText("Currently Disabled:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(lblDisabled, gridBagConstraints);

        txtCurrentlyEnabled.setEditable(false);
        txtCurrentlyEnabled.setText(String.valueOf(currentStructure.getStructureAmount()) );
        txtCurrentlyEnabled.addActionListener(this::txtCurrentlyEnabledActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(txtCurrentlyEnabled, gridBagConstraints);

        txtCurrentlyDisabled.setText(String.valueOf(currentStructure.getInactiveStructureAmount()) );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(txtCurrentlyDisabled, gridBagConstraints);

        btnConfirmConfiguration.setText("Confirm New Configuration");
        btnConfirmConfiguration.addActionListener(this::btnConfirmConfigurationActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        jPanel1.add(btnConfirmConfiguration, gridBagConstraints);

        lblConfigurationHeader.setText("Production Configuration: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(lblConfigurationHeader, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        add(jPanel1, gridBagConstraints);

        btnBuildStructure.setText("Build Structure");
        btnBuildStructure.addActionListener(this::btnBuildStructureActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        add(btnBuildStructure, gridBagConstraints);

        btnDeconstructStructure.setText("Demolish Structure");
        btnDeconstructStructure.addActionListener(this::btnDeconstructStructureActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        add(btnDeconstructStructure, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCurrentlyEnabledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurrentlyEnabledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurrentlyEnabledActionPerformed

    private void btnBuildStructureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuildStructureActionPerformed
        
        // Get display message based on structure name
        String displayMessage = "How many " + currentStructure.getDisplayName() + "(s) to build?"; 
        
        int structuresToBuild = structureDialogWithResources(displayMessage, currentStructure, "Build Costs:", "Are you sure? ");
        
        // As convention; 
        if (structuresToBuild == -1) {
            JOptionPane.showMessageDialog(null, "Build order cancelled.", "Result", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            // Attempt to build structures based off currentStructure and structuresToBuild. 
            BuildableBody.buildStructure(currentStructure.getParentBuildableBody(), currentStructure, structuresToBuild);
        }
        
        txtCurrentlyEnabled.setText(Integer.toString(currentStructure.getStructureAmount()));
    }//GEN-LAST:event_btnBuildStructureActionPerformed

    private void btnDeconstructStructureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeconstructStructureActionPerformed
        // Get display message based on structure name
        String displayMessage = "How many " + currentStructure.getDisplayName() + "(s) to demolish?"; 
        
        int structuresToBuild = structureDialogWithResources(displayMessage, currentStructure, "Resources you would earn:", "Are you sure? ");
        
        // As convention; 
        if (structuresToBuild == -1) {
            JOptionPane.showMessageDialog(null, "Demolition order cancelled.", "Result", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            // Attempt to build structures based off currentStructure and structuresToBuild. 
            BuildableBody.destroyStructure(currentStructure.getParentBuildableBody(), currentStructure, structuresToBuild);
        }
        txtCurrentlyEnabled.setText(Integer.toString(currentStructure.getStructureAmount()));
    }//GEN-LAST:event_btnDeconstructStructureActionPerformed

    private void btnConfirmConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmConfigurationActionPerformed
        String userInput = txtCurrentlyDisabled.getText(); 
        int structureDisableAmount; 
        try {
            structureDisableAmount = Integer.parseInt(userInput); 
            if (structureDisableAmount < 0) {
                JOptionPane.showMessageDialog(null, "Please enter a number greater than 0", "Result", JOptionPane.WARNING_MESSAGE); 
            }
            else {
                currentStructure.setInactiveStructureAmount(structureDisableAmount);
                txtCurrentlyDisabled.setText(Integer.toString(currentStructure.getInactiveStructureAmount()));
            }
        }
        catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter an actual number", "Result", JOptionPane.WARNING_MESSAGE); 
        }
        
        txtCurrentlyDisabled.setText(Integer.toString(currentStructure.getInactiveStructureAmount()));
    }//GEN-LAST:event_btnConfirmConfigurationActionPerformed
    
    
    /**
     * Obtains a structureAmount value for other methods within this class by displaying a dialog input box for resource amount. Comes with input error handling and user input confirmation dialog. 
     * @param valueInputDisplayMessage Message to display on initial integer input dialog. 
     * @param currentStructure Current structure to calculate / obtain final resource table for display in confirmation dialog. 
     * @param beforeResourcesMessage String to show before the resource table in the confirmation dialog.
     * @param afterResourcesMessage String to show after the resource table in the confirmation dialog.
     * @return Returns user input for structures to build if it is valid and confirmed. Returns -1 if user did not confirm value or closed the dialog boxes. 
     */
    int structureDialogWithResources(String valueInputDisplayMessage, Structure currentStructure, String beforeResourcesMessage, String afterResourcesMessage) {
        
        // Flag for if a valid input has been entered and confirmed; 
        boolean validInput = false; 
        
        // User input string; 
        String userInput = ""; 
        
        // Number of structures to build
        int structuresToBuild = 0; 
        
        // Status from confirmation dialog & message in dialoue respectively. 
        int status; 
        String[] message; 
        
        // While no valid input has been registered; continuously loop until a valid input is entered and is confirmed. 
        while (!validInput) {
            // Try-block to catch NumberFormatException from Integer.parseInt(). 
            try {
                // Get structuresToBuild from input dialog; 
                userInput = (String) JOptionPane.showInputDialog(valueInputDisplayMessage);
                structuresToBuild = Integer.parseInt(userInput); 
                
                // If user input was less than -1; then provide this error message. 
                if (structuresToBuild <= 0) {
                    JOptionPane.showMessageDialog(null, "Please enter a valid number greater than 0.","Result", JOptionPane.WARNING_MESSAGE);
                    continue; 
                }
                
                // If not, continue: 
                // Get resource cost confirm message text via getScaledResourceReceipt. 
                message= Resource.getScaledResourceReceipt(currentStructure.getStructureCosts(structuresToBuild),beforeResourcesMessage, afterResourcesMessage); 
                
                // Get user confirmation that this is the amount of structures that they want to build. 
                status = JOptionPane.showConfirmDialog(null, message, "Resource Costs", JOptionPane.YES_NO_OPTION); 
                switch(status) {
                    case JOptionPane.YES_OPTION: 
                        validInput = true; 
                        break; 
                    case JOptionPane.NO_OPTION: 
                        break; 
                    case JOptionPane.CLOSED_OPTION: 
                        return -1; 
                }
            }
            catch (java.lang.NumberFormatException e) {
                
                // userInput will only equal null if the user close the initial showInputDialog dialog screen. 
                if (userInput==null) {
                    return -1;
                }
                else {
                    JOptionPane.showMessageDialog(null, "Please enter a valid number.");
                }
                
            }
            
        }
        return structuresToBuild; 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuildStructure;
    private javax.swing.JButton btnConfirmConfiguration;
    private javax.swing.JButton btnDeconstructStructure;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConfigurationHeader;
    private javax.swing.JLabel lblDisabled;
    private javax.swing.JLabel lblEnabled;
    private javax.swing.JLabel lblInputOutput;
    private javax.swing.JTextField txtCurrentlyDisabled;
    private javax.swing.JTextField txtCurrentlyEnabled;
    private javax.swing.JTextArea txtInputOutputArea;
    // End of variables declaration//GEN-END:variables
}
